package com.quiz_moviles.Estructuras;

public enum SERVICIOS {
    INSERTAR_ESTUDIANTE,
    LISTAR_ESTUDIANTES,
    ELIMINAR_ESTUDIANTE,
    MODIFICAR_ESTUDIANTE,
    LISTAR_CURSOS,
    LISTAR_CURSOS_POR_ESTUDIANTE,
}
